export const ALERT = 'ALERT'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_LOCATION_ORIGINAL = 'SET_LOCATION_ORIGINAL'
export const MODAL_TOGGLE = 'MODAL_TOGGLE'
export const MAP_FILTER = 'MAP_FILTER'

