export const ALERT = 'ALERT'
export const MAP_FILTER = 'MAP_FILTER'
export const MAP_SET_LOCATION = 'MAP_SET_LOCATION'
export const MAP_SET_LOCATION_ORIGINAL = 'MAP_SET_LOCATION_ORIGINAL'
export const MAP_SET_ZOOM_LEVEL = 'MAP_SET_ZOOM_LEVEL'
export const MODAL_TOGGLE = 'MODAL_TOGGLE'

